language: node_js
before_script:
  - npm install -g backslide
script: ./build.sh
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
